import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { getLangFromCookie } from '@/utils/getLang.server'
import { getTranslations } from '@/i18n/translate'
import { I18nProvider } from '@/context/i18n-context'
import { ThemeProvider } from '@/components/theme-provider'
import { SessionProvider } from 'next-auth/react'
import StoreProvider from '@/context/store.provider'
import { Toaster } from 'sonner'
import OnlineGuard from '@/guards/online-guard'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  const lang = await getLangFromCookie()
  const { dictionary } = await getTranslations(lang, [
    'banks',
    'login',
    'validation_login',
    'doc_beneficiario',
    'home',
    'sidebar',
    'buttons',
    'messages',
    'notifications_page',
    'notifications_new_page',
    'tables',
    'required-fields',
    'partners',
    'clients',
    'common',
    'documents',
    'account-form',
    'upload-documents',
    'voucher-page'
  ])

  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <StoreProvider>
            <I18nProvider locale={lang} dictionary={dictionary}>
              <ThemeProvider
                attribute='class'
                defaultTheme='system'
                enableSystem
                disableTransitionOnChange
              >
                <OnlineGuard>
                  {children}
                  {modal}
                </OnlineGuard>
                <Toaster richColors position='top-center' />

              </ThemeProvider>
            </I18nProvider>
          </StoreProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
